#!/usr/bin/env perl
#
# yavi -- Front end to the Parse::Yavi module
#

=head1 NAME

yavi - A perl front-end to the Parse::Yavi module

=head1 SYNOPSIS

    yavi [options] grammar[.yv]
    yavi --help
    yavi --version

        -m module   Give your parser module the name <module>
                    Default is <grammar>
        -o outfile  Create the file <outfile> for your parser module
                    Default is autoload/{grammar}.vim or,
                    if -m A#Module#Name is specified, Name.vim
        --help      Display this help message

        grammar     The grammar file.

=head1 DESCRIPTION

=head1 OPTIONS IN DETAIL

=over 4

=item I<-v>

=cut

require 5.004;

use utf8;
use strict;
use warnings;
use Carp qw/croak cluck/;
use Getopt::Long qw/:config posix_default no_ignore_case gnu_compat/;
use Pod::Usage;
use Parse::Yavi;
use IO::File;
use File::Basename;

my %opts;
GetOptions(
    \%opts, qw/
    help|h|man|usage|
    module|m=s
    outfile|o=s
    debug
/);
pod2usage(2) if $opts{help};
pod2usage(2) if @ARGV <= 0;

my ($grammarfile)= @ARGV;

unless(-f $grammarfile)
{
    die "File not exist `$grammarfile'.";
}

$opts{outfile}||= basename($grammarfile) . '.vim';

my $yavi= Parse::Yavi->new;

my $data= $yavi->parse(IO::File->new($grammarfile));

$yavi->generate($data, IO::File->new($opts{outfile}));

1;
